### PR TITLE
Plot FNHI

### PR DESCRIPTION
**Pull request by alxogm**
@londumas  I think this is ready for review. I've only checked up to the redshift distribution. 
I think we have to agree in a couple of things for the quickquasar output format, for the following runs. 

I've put here the script to create the catalog, but I'm not sure if this could be better located in desisim, as it is the script to make the QSO catalog... what do you think?

### CODE REVIEW

**Comment by londumas** [comment]
@alxogm, Thank you for the PR, I just copied the new codes and merged it to master:
https://github.com/igmhub/desi_QA/blob/master/Mocks/QA_DLA.ipynb.
It looks good! Thanks.
Could you have a look and tell me is this is ok?

For `Mocks/genDLAcatalog.py`, I would rather this repository made only for QA.
The mock team is taking care of creating a code to have the catalog.

**Comment by alxogm** [comment]
Hi @londumas. Yes I think it looks good. 
I thought that all those functions being defined in the notebook, to make the histograms, or the fNHI,  and in this case to create the catalog in case it doesn't exist, can be moved to a script  so that the notebook is easier to read. What mock team you refer to?

**Comment by londumas** [comment]
>I thought that all those functions being defined in the notebook, to make the histograms, or the fNHI, >and in this case to create the catalog in case it doesn't exist, can be moved to a script so that the >notebook is easier to read.
I like everything in the notebook so anybody can run it by itself, without calling another library

>What mock team you refer to?
London mock team

**Comment by alxogm** [comment]
I see... Ok. BTW. I didn't see before that checks of Codacy, it is nice to have it. I'll try to follow it next time. So you can delete the branch then. 

Thanks

**Comment by londumas** [comment]
@alxogm, Thank you very much for the work.

**Pull request closed without merging**
